# After PV/PVC Created
apiVersion: v1
kind: Pod
metadata:
  name: read
spec:
  containers:
  - name: read
    image: busybox 
    command: ["/bin/sh"] 
    args: ["-c", "while true; do sleep 3600; done"]
    volumeMounts:
    - name: efs-volume
      mountPath: /data
  volumes:
  - name: efs-volume
    persistentVolumeClaim:
      claimName: read-pvc